name: MCCRestart
version: 1.2.4
author: Cr@zy
main: fr.crazyws.mccrestart.MCCRestart
commands:
  mccrestart:
    description: All MCCRestart commands
    usage: |
      /<command> help - List MCCRestart commands
      /<command> reload - Reload the plugin configuration
      /<command> next - Give the next time to restart
      /restart - Restart the server immediately
      /restart 59:59 - Restart after a delay (minutes:seconds)
      /restart 59:59 "reason" - Restart after a delay with a reason
  restart:
    description: Restart the server immediately
    usage: |
      /<command> - Restart the server immediately
      /<command> 59:59 - Restart after a delay (minutes:seconds)
      /<command> 59:59 "reason" - Restart after a delay with a reason
      /<command> cancel - Cancel a manual restart