name: MCCRestart
version: 1.2.0
author: Cr@zy
main: fr.crazyws.mccrestart.MCCRestart
commands:
  mccrestart:
    description: All MCCRestart commands
    usage: |
      /<command> help - List MCCRestart commands
      /<command> on|off - Actives/deactivates MCCRestart
      /<command> reload - Reload the plugin configuration
      /<command> next - Give the next time to restart
      /restart - Restart the server immediately
  restart:
    description: Restart the server immediately
    usage: /<command>